# Load household characteristics dataset from INEC
household_characteristics: `http://www.inec.go.cr/ingresos-y-gastos-de-hogares/ingresos-de-los-hogares`

Education: `http://www.inec.go.cr/educacion`

In [1]:
import preprocessing

In [2]:
household_characteriscits = preprocessing.INECDataSet('household_characteristics')
print(household_characteriscits.get_dataset_description())
hh_char = household_characteriscits.get_dataset()
hh_char.head()

Start to load data...
Processing... Please wait...

/Users/scott/dev/ece143/preprocessing.py:144: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  year_df['Category'] = year_df['Category'].apply(lambda x: self.category_translation[x])
/Users/scott/dev/ece143/preprocessing.py:145: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  year_df['year'] = year

Main characteristics of households and people
By quintiles of household income per capita
According to planning region
July 2010-2017
(Excludes domestic service and pensioners)

,index,Category,Total,Quintil 1,Quintil 2,Quintil 3,Quintil 4,Quintil 5,region,year
0,14,Total people,4551553,1052105,959510,954140,842427,743371,Whole Costa Rica,2010
1,15,Total households,1289716,257879,258035,257935,257731,258136,Whole Costa Rica,2010
2,16,Members per household,3.52911,4.07984,3.71853,3.69915,3.26863,2.87976,Whole Costa Rica,2010
3,17,Work force by household,1.58406,1.17657,1.43144,1.78882,1.81789,1.70563,Whole Costa Rica,2010
4,18,Occupied by household,1.46817,0.935943,1.29298,1.6794,1.76074,1.67181,Whole Costa Rica,2010

In [4]:
education = preprocessing.INECDataSet('edu')
print(education.get_dataset_description())
edu = education.get_dataset()
edu.head()

Start to load data...
Costa Rica: Population from 5 to 24 years old, percentage distribution

For attendance at regular education
According to planning area and region

,index,region,5-24 total,5-24 not attend%,5-24 attend%,5-12 total,5-12 not attend%,5-12 attend%,13-17 total,13-17 not attend%,13-17 attend%,18-24 total,18-24 not attend%,18-24 attend%,year
0,8,Total,1646747,29.6364,70.3636,581477,3.86223,96.1378,436865,16.864,83.136,628405,62.365,37.635,2010
1,11,Urbana,1158249,28.9644,71.0356,389829,3.00568,96.9943,297708,14.0668,85.9332,470712,59.8848,40.1152,2010
2,12,Rural,488498,31.2296,68.7704,191648,5.60455,94.3955,139157,22.8483,77.1517,157693,69.7685,30.2315,2010
3,15,Central,983942,29.5238,70.4762,328945,2.8184,97.1816,249967,14.4067,85.5933,405030,60.5422,39.4578,2010
4,16,Chorotega,131340,30.0122,69.9878,47884,4.88472,95.1153,36693,18.5076,81.4924,46763,64.7692,35.2308,2010